apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-record-mysql-pv
spec:
  storageClassName: record-mysql
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data
